name: Fetch Daily Report
on:
  schedule:
    - cron: "0 6 * * *" # Run every day at 6 UTC
  push:
    branches:
      - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install necessary dependecies
        run: |
          pip install -r requirements.txt
          
      - name: Run Application
        run: |
          python app.py

      - name: Add report to git
        run: |
          git pull 
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          git add -f data/meta.csv
          git add -f data/summary.csv
          git commit -m "Updated Report"
          git push
